[package]
name = "svt_yaml"
version = "0.9.0"
authors = ["jam1garner <8260240+jam1garner@users.noreply.github.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
smash-svt = { path = "../smash-svt", features = ["serde"] }
serde_yaml = { version = "0.9" }
